accent = "#F2293A"
cursor = "#F2293A"
foreground = "#E7E9E7"
background = "#08090B"
selection_foreground = "#08090B"
selection_background = "#F2293A"
color0 = "#08090B"
color1 = "#C51F31"
color2 = "#8DA399"
color3 = "#B8B6A8"
color4 = "#65737E"
color5 = "#A86C74"
color6 = "#8DA399"
color7 = "#E7E9E7"
color8 = "#30343A"
color9 = "#F2293A"
color10 = "#B3C9B6"
color11 = "#D3D2C5"
color12 = "#8AA7B6"
color13 = "#D58B94"
color14 = "#B7D0C1"
color15 = "#FFFFFF"
