general {
    col.active_border = rgb(F2293A)
    col.inactive_border = rgb(30343A)
    border_size = 2
    gaps_in = 4
    gaps_out = 6
}

group {
    col.border_active = rgba(F2293Aee)
    col.border_inactive = rgb(30343A)
    groupbar {
        col.active = rgba(F2293Aff)
        col.inactive = rgba(111418dd)
        text_color = rgb(08090B)
        text_color_inactive = rgb(E7E9E7)
    }
}

decoration {
    rounding = 0
    shadow {
        enabled = true
        render_power = 4
        range = 16
        color = rgba(00000080)
    }
}
